// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Terminar.Modules.Registrations.Infrastructure;

#nullable disable

namespace Terminar.Modules.Registrations.Infrastructure.Migrations
{
    [DbContext(typeof(RegistrationsDbContext))]
    partial class RegistrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registrations")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Terminar.Modules.Registrations.Domain.Registration", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime?>("CancelledAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<Guid>("CourseId")
                    .HasColumnType("uuid");

                b.Property<string>("ParticipantEmail")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)");

                b.Property<string>("ParticipantName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Guid?>("RegisteredByStaffId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("RegisteredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("RegistrationSource")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<Guid>("SelfCancellationToken")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CourseId");

                b.HasIndex("TenantId");

                b.ToTable("Registrations", "registrations");
            });
#pragma warning restore 612, 618
        }
    }
}
